// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpwlxdeorevbxrvfmkam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdwd2x4ZGVvcmV2YnhydmZta2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzYxNjAsImV4cCI6MjA2NDExMjE2MH0.AabYV7t_yNSl3LngEBRfFh0EbZaNtGeH4lOLrN5dFCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);